config/routes.rb
Youtour::Application.routes.draw do
get 'fb_login', to: 'fb_sessions#new_fb_session'
  resources :users do
    get 'reqs', to: 'trips#reqs', :action => ":index", :controller => ":trips"
    get 'change_password', to: 'users#change_password', :action => ":edit", :controller => ":users"
    resources :tours do
      resources :trips 
    end
  end
  resources :user_sessions
  root :to => 'pages#home'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/' => 'pages#home'
  match 'home' => 'pages#home'
  match 'contact' => 'pages#contact'
  match 'aboutus' => 'pages#aboutus'
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :request_by, :status, :tour_id
  belongs_to :tour
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:tour_id])
    @trips = @tour.trips.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:tour_id])
    @trip = @tour.trips.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:tour_id])
    @trip = @tour.trips.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:tour_id])
    @trip = @tour.trips.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:tour_id])
    @trip = @tour.trips.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to user_tour_trips_path, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:tour_id])
    @trip = @tour.trips.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to user_tour_trip_path(@user,@tour,@trip), notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:tour_id])
    @trip = @tour.trips.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to user_tour_trips_url }
      format.json { head :no_content }
    end
  end

  def reqs
    p "#############################################################"
    @trips = Trip.find(:all, :conditions => {:request_by => current_user.id}) 
    respond_to do |format|
      format.html 
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for([@user, @tour, @trip]) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tour_id %><br />
    <%= f.text_field :tour_id %>
  </div>
  <div class="field">
    <%= f.label :request_by %><br />
    <%= f.text_field :request_by %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', user_tour_trip_path(@user,@tour,@trip) %> |
<%= link_to 'Back', user_tour_trips_path(@user,@tour) %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Tour</th>
    <th>Request by</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.id %></td>
    <td><%= trip.tour_id %></td>
    <td><%= trip.request_by %></td>
    <td><%= trip.status %></td>
    <td><%= link_to 'Show', user_tour_trip_path(@user,@tour,trip) %></td>
    <td><%= link_to 'Edit', edit_user_tour_trip_path(@user,@tour,trip) %></td>
    <td><%= link_to 'Destroy', [@user,@tour,trip], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip', new_user_tour_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tour_trips_path %>

app/views/trips/reqs.html.erb
<h1>My requests</h1>
<% if @trips %>
  <table>
    <tr>
      <th>Id</th>
      <th>Tour</th>
      <th>Request by</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.id %></td>
      <td><%= trip.tour_id %></td>
      <td><%= trip.request_by %></td>
      <td><%= trip.status %></td>
      <td><%= link_to 'Show', user_tour_trip_path(@user,@tour,trip) %></td>
      <td><%= link_to 'Edit', edit_user_tour_trip_path(@user,@tour,trip) %></td>
      <td><%= link_to 'Destroy', [@user,@tour,trip], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>
<% else %>
  nothing interesting here!!
<% end %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tour:</b>
  <%= @trip.tour_id %>
</p>

<p>
  <b>Request by:</b>
  <%= @trip.request_by %>
</p>

<p>
  <b>Status:</b>
  <%= @trip.status %>
</p>


<%= link_to 'Edit', edit_user_tour_trip_path(@user,@tour,@trip) %> |
<%= link_to 'Back', user_tour_trips_path(@user,@tour) %>