config/routes.rb
Youtour::Application.routes.draw do
get 'fb_login', to: 'fb_sessions#new_fb_session'
  resources :users do
    get 'reqs', to: 'trips#reqs', :action => ":index", :controller => ":trips"
    get 'change_password', to: 'users#change_password', :action => ":edit", :controller => ":users"
    resources :tours do
      resources :trips 
    end
  end
  resources :user_sessions
  root :to => 'pages#home'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/' => 'pages#home'
  match 'home' => 'pages#home'
  match 'contact' => 'pages#contact'
  match 'aboutus' => 'pages#aboutus'
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  attr_accessible :desp, :doj, :from_loc, :to_loc, :user_id
  belongs_to :user
  has_many :trips
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  # GET /tours
  # GET /tours.json
  def index
    @user = User.find(params[:user_id])
    @tours = @user.tours.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tours }
    end
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    @user=User.find(params[:user_id])
    @tour = @user.tours.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tour }
    end
  end

  # GET /tours/new
  # GET /tours/new.json
  def new
    @user = User.find(params[:user_id])
    @tour = @user.tours.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tour }
    end
  end

  # GET /tours/1/edit
  def edit
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:id])
  end

  # POST /tours
  # POST /tours.json
  def create
    @user = User.find(params[:user_id])
    @tour = @user.tours.new(params[:tour])

    respond_to do |format|
      if @tour.save
        format.html { redirect_to user_tours_path, notice: 'Tour was successfully created.' }
        format.json { render json: @tour, status: :created, location: user_tours_path }
      else
        format.html { render action: "new" }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tours/1
  # PUT /tours/1.json
  def update
    @user = User.find(params[:id])
    @tour = @user.tours.find(params[:id])
    params[:tour][:user_id]=current_user.id

    respond_to do |format|
      if @tour.update_attributes(params[:tour])
        format.html { redirect_to user_tours_path, notice: 'Tour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @user = User.find(params[:user_id])
    @tour = @user.tours.find(params[:id])
    @tour.destroy

    respond_to do |format|
      format.html { redirect_to user_tours_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_for([@user,@tour]) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :from_loc %><br />
    <%= f.text_field :from_loc %>
  </div>
  <div class="field">
    <%= f.label :to_loc %><br />
    <%= f.text_field :to_loc %>
  </div>
  <div class="field">
    <%= f.label :doj %><br />
    <%= f.text_field :doj %>
  </div>
  <div class="field">
    <%= f.label :desp %><br />
    <%= f.text_field :desp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', user_tours_path(@user,@tour) %> |
<%= link_to 'Back', user_tours_path %>

app/views/tours/index.html.erb
<h1>Listing tours</h1>

<table>
  <tr>
    <th>Id</th>
    <th>User</th>
    <th>From loc</th>
    <th>To loc</th>
    <th>Doj</th>
    <th>Desp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tours.each do |tour| %>
  <tr>
    <td><%= tour.id %></td>
    <td><%= tour.user_id %></td>
    <td><%= tour.from_loc %></td>
    <td><%= tour.to_loc %></td>
    <td><%= tour.doj %></td>
    <td><%= tour.desp %></td>
    <td><%= link_to 'Show', user_tour_path(@user,tour) %></td>
    <td><%= link_to 'Edit', edit_user_tour_path(@user,tour) %></td>
    <td><%= link_to 'Destroy', [@user,tour], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tour', new_user_tour_path %>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @tour.user_id %>
</p>

<p>
  <b>From loc:</b>
  <%= @tour.from_loc %>
</p>

<p>
  <b>To loc:</b>
  <%= @tour.to_loc %>
</p>

<p>
  <b>Doj:</b>
  <%= @tour.doj %>
</p>

<p>
  <b>Desp:</b>
  <%= @tour.desp %>
</p>


<%= link_to 'Edit', edit_user_tour_path(@tour) %> |
<%= link_to 'Back', user_tours_path %>