config/routes.rb
Youtour::Application.routes.draw do
get 'fb_login', to: 'fb_sessions#new_fb_session'
  resources :users do
    get 'reqs', to: 'trips#reqs', :action => ":index", :controller => ":trips"
    get 'change_password', to: 'users#change_password', :action => ":edit", :controller => ":users"
    resources :tours do
      resources :trips 
    end
  end
  resources :user_sessions
  root :to => 'pages#home'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/' => 'pages#home'
  match 'home' => 'pages#home'
  match 'contact' => 'pages#contact'
  match 'aboutus' => 'pages#aboutus'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Youtour</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <%= link_to "Home", home_path %> |
  <%= link_to "About Us", aboutus_path %> |
  <%= link_to "Keep in touch", contact_path %> |
  <% if current_user %>
    <%= link_to "Edit Profile", edit_user_path(current_user)%> |
    <%= link_to "Change Password", user_change_password_path(current_user) %>|
    <%= link_to "Logout", logout_path %>
  <% else %>
    <%= link_to "Register", new_user_path %> |
    <%= link_to "Login", login_path %>
  <% end %>
</div>
<%if current_user%>
<div id="current_user" style="float:right">
  <%= current_user.name %>
</div>
<%end%>
<%= yield %>

</body>
</html>